export default [
	{ name: 'Hài Hước' },
	{ name: 'Viễn Tưởng' },
	{ name: 'Hành Động' },
	{ name: 'Phiêu Lưu' },
	{ name: 'Tâm Lý' },
	{ name: 'Hình Sự' },
	{ name: 'Kinh Dị' },
	{ name: 'Điện Ảnh' },
	{ name: 'Âm Nhạc' },
	{ name: 'Khoa học Tài liệu' },
	{ name: 'Võ Thuật' },
	{ name: 'Chiến Tranh' },
	{ name: 'Hoạt Hình' },
	{ name: 'Thần Thoại' },
	{ name: 'Cổ Trang' },
	{ name: 'Thuyết Minh' },
	{ name: 'Thiếu nhi' },
	{ name: 'Hài Việt' },
	{ name: 'TV Show' }
]
